### ISSUE TITLE
Refresh Token creation time calculation in mixins.py

### ISSUE THREAD

**Issue by zullrajas** [oscarychen/django-oauth-toolkit-cookie-refresh#3]
Hey @oscarychen,

Thanks for this really neat and compact plugin!

While trying to use it in my solution I observed that when the `refresh_token` endpoint is called the refresh token creation time is computed using `oauth2_settings.ACCESS_TOKEN_EXPIRE_SECONDS` setting (see https://github.com/oscarychen/django-oauth-toolkit-spa/blob/master/oauth_toolkit_spa/mixins.py#L61). 

Shouldn't it use the `oauth2_settings.REFRESH_TOKEN_EXPIRE_SECONDS` instead or is this the intended implementation? Something along the lines of:
```
refresh_token_creation_time = timezone.now() - timedelta(seconds=oauth2_settings.REFRESH_TOKEN_EXPIRE_SECONDSor 36000)
```

In the meantime of course I can override the view for the refresh token action, but I wanted to highlight this so maybe we can fix it in case it is not intended.

Thanks!

**Comment by oscarychen** [comment]
@zullrajas Thanks for noticing this. It will be updated in the next update v1.0.1
